name: Deploy Docs

on:
  push:
    branches: [ "main" ]

jobs:
  docs:
    name: Build and deploy docs.

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install sphinx furo

      - name: Sphinx build
        run: |
          git worktree add docs/_build/html gh-pages
          cd docs
          make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
