name: Deploy Docs

on:
  push:
    branches: [ "main" ]

jobs:
  docs:
    name: Build and deploy docs.

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install sphinx furo

      - name: git config
        run: |
          git config user.email "Stefanie Molin"
          git config user.name "24376333+stefmolin@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Sphinx build
        run: |
          git worktree add docs/_build/html gh-pages
          cd docs
          make html

      - name: Deploy docs
        run: |
          cd docs/_build/html
          git add --all
          git commit -m "Update documentation."
          git push origin gh-pages
